server:
  port: 8082

spring:
  application:
    name: INCIDENT-SERVICE

  datasource:
    url: ${INCIDENT_DB_URL:jdbc:postgresql://localhost:5432/incidentiq_incident_db}
    username: ${INCIDENT_DB_USERNAME:postgres}
    password: ${INCIDENT_DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

jwt:
  secret: aW5jaWRlbnRpcXN1cGVyc2VjcmV0a2V5aW5jaWRlbnRpcXN1cGVyc2VjcmV0a2V5MTIz
  expiration: 86400000

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET}

eureka:
  instance:
    hostname: ${INCIDENT_SERVICE_HOSTNAME:localhost}
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}